version: '3.7'
services:
  spectura:
    environment:
      "DECAP_URL": "http://decap:4531"
      "USE_SIGNATURES": "false"
      "SIGNING_SECRET": "secret"
      "SIGNING_KEY": "key"
      "SIGNING_UNIQUE_NAME": "jix_spectura"
      "BG_RATE_LIMIT_TIME": "120s"
      "REFRESH_TASK_DELAY": "10s"
      "AUTO_REFRESH_AFTER": "30s"
      "SCHEDULE_INTERVAL": "30s"
      "WEBHOOK_URL": "http://webhook-tester:5000/webhook"
      "ADMIN_TOKEN": "test"
    volumes:
      - "./templates:/templates"
    depends_on:
      - decap
    build:
      context: .
    ports:
      - 19165:19165

  decap:
    image: jobindex/decap:0.15
    expose:
      - 4531 # expose to spectura but not to host system

  webhook-tester:
    build:
      context: webhook-tester
    environment:
      PYTHONUNBUFFERED: 1
    expose:
        - "5000"
